before_commands:
    - "composer install --prefer-source"

filter:
    excluded_paths: [vendor/*, tests/*]

tools:
    external_code_coverage:
      # 15 minutes
      timeout: 900

    php_analyzer: true
    php_changetracking: true
    php_code_sniffer: true
    php_cpd: true
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend:
        excluded_dirs: [vendor, tests/*]
    php_sim: true
    sensiolabs_security_checker: true
