before_commands:
    - "composer install --prefer-source"

filter:
    excluded_paths: [vendor/*, tests/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor, tests/*]
    external_code_coverage: true
